version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: reserva_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: reserva_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reserva-net

  redis:
    image: redis:alpine
    container_name: reserva_redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - reserva-net

networks:
  reserva-net:

volumes:
  postgres_data: